class Database:
    def __init__(self):
        self.db_path = '/var/data/bot_database.db'  # Updated persistent disk path
        # Additional initialization code...

    # Other methods for the Database class...
